jobs:
- job: Coverity
  pool:
    name: private-windows
  workspace:
    clean: all
  steps:
  - task: SynopsysPolaris@1
    inputs:
      polarisService: 'Polaris connection'
      polarisCommand: 'analyze -w'